name: deploy
on:
  push:
    branches:
      - master
jobs:
  build-terraform-provider-cloudflare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # git clone -b cloudflare_worker_script.r2_bucket_binding --single-branch https://github.com/yonran/terraform-provider-cloudflare
        with:
          repository: yonran/terraform-provider-cloudflare
          ref: cloudflare_worker_script.r2_bucket_binding
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'
          cache: true
      - run: go build
      - uses: actions/upload-artifact@v3
        with:
          name: terraform-provider-cloudflare
          path: terraform-provider-cloudflare
          retention-days: 1
  build-terraform-provider-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # - run: git clone -b cloudflare-no-s3-object-tags --single-branch https://github.com/yonran/terraform-provider-aws
        with:
          repository: yonran/terraform-provider-aws
          ref: cloudflare-no-s3-object-tags
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'
          cache: true
      - run: go build
      - uses: actions/upload-artifact@v3
        with:
          name: terraform-provider-aws
          path: terraform-provider-aws
          retention-days: 1
  terraform-plan:
    runs-on: ubuntu-latest
    needs: [build-terraform-provider-cloudflare, build-terraform-provider-aws]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: terraform-provider-cloudflare
      - uses: actions/download-artifact@v3
        with:
          name: terraform-provider-aws
      - run: chmod +x terraform-provider-cloudflare terraform-provider-aws
      - run: |-
          cat <<EOF > ~/.terraformrc
          # override with self-built plugins
          # https://www.terraform.io/cli/config/config-file#development-overrides-for-provider-developers
          provider_installation {
            dev_overrides {
              "cloudflare/cloudflare" = "$(pwd)"
              "hashicorp/aws" = "$(pwd)"
            }

            # For all other providers, install them directly from their origin provider
            # registries as normal. If you omit this, Terraform will _only_ use
            # the dev_overrides block, and so no other providers will be available.
            direct {}
          }
          # enable plugin cache to save time downloading
          # https://www.terraform.io/cli/config/config-file#provider-plugin-cache
          plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
          EOF
      - name: Cache cargo checkouts
        id: cache-cargo
        uses: actions/cache@v3
        env:
          cache-name: cache-cargo
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache terraform plugins
        id: terraform-plugins
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-build-terraform-plugins
          restore-keys: |
            ${{ runner.os }}-build-terraform-plugins
      - run: mkdir -p ~/.terraform.d/plugin-cache
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: _setup/package-lock.json
      - run: npm ci
        working-directory: _setup
      - run: npm test
        working-directory: _setup
      - run: npm run build-images
        working-directory: _setup
      - run: cargo install cobalt-bin@0.18.0
      - run: cobalt build
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: _cloudflare_worker/package-lock.json
      - run: npm ci
        working-directory: _cloudflare_worker
      - run: npx tsc
        working-directory: _cloudflare_worker
      - run: terraform -chdir=_terraform init
        env:
          TF_VAR_account_id = ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          TF_VAR_cloudflare_api_token = ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_backend_access_key_id = ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          TF_VAR_backend_secret_access_key = ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
      - run: terraform -chdir=_terraform plan -no-color -out=../tfplan
        env:
          TF_VAR_account_id = ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          TF_VAR_cloudflare_api_token = ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_backend_access_key_id = ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          TF_VAR_backend_secret_access_key = ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
      - run: openssl enc -aes-256-cbc -pbkdf2 -iter 20000 -in tfplan -out tfplan.enc -pass env:TFPLAN_KEY
        env:
          TFPLAN_KEY: ${{ secrets.ARTIFACT_ENCRYPTION_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          name: terraform-files-and-dependencies
          # terraform files, tfplan file, and sources of aws_s3_object
          path: |
            _terraform/
            tfplan.enc
            _site/
          retention-days: 1
  terraform-apply:
    runs-on: ubuntu-latest
    environment: production
    needs: [build-terraform-provider-cloudflare, build-terraform-provider-aws, terraform-plan]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: terraform-provider-cloudflare
      - uses: actions/download-artifact@v3
        with:
          name: terraform-provider-aws
      - run: chmod +x terraform-provider-cloudflare terraform-provider-aws
      - uses: actions/download-artifact@v3
        with:
          name: terraform-files-and-dependencies
      - run: openssl dec -aes-256-cbc -pbkdf2 -iter 20000 -in tfplan.enc -out tfplan -pass env:TFPLAN_KEY
        env:
          TFPLAN_KEY: ${{ secrets.ARTIFACT_ENCRYPTION_PASSWORD }}
      - name: Cache terraform plugins
        id: terraform-plugins
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-build-terraform-plugins
          restore-keys: |
            ${{ runner.os }}-build-terraform-plugins
      - run: |-
          cat <<EOF > ~/.terraformrc
          # override with self-built plugins
          # https://www.terraform.io/cli/config/config-file#development-overrides-for-provider-developers
          provider_installation {
            dev_overrides {
              "cloudflare/cloudflare" = "$(pwd)"
              "hashicorp/aws" = "$(pwd)"
            }

            # For all other providers, install them directly from their origin provider
            # registries as normal. If you omit this, Terraform will _only_ use
            # the dev_overrides block, and so no other providers will be available.
            direct {}
          }
          # enable plugin cache to save time downloading
          # https://www.terraform.io/cli/config/config-file#provider-plugin-cache
          plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
          EOF
      - run: terraform -workdir=_terraform init
      - run: terraform -workdir=_terraform apply terraform.plan
        env:
          TF_VAR_account_id = ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          TF_VAR_cloudflare_api_token = ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_backend_access_key_id = ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          TF_VAR_backend_secret_access_key = ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
