name: test-build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: _setup/package-lock.json
      - run: npm ci
        working-directory: _setup
      - run: npm test
        working-directory: _setup
      - run: npm run build-images
        working-directory: _setup
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: _cloudflare_worker/package-lock.json
      - run: npm ci
        working-directory: _cloudflare_worker
      - run: npx tsc --noEmit
        working-directory: _cloudflare_worker
      - run: terraform fmt -check -workdir=_terraform
